name: LobbyCompass2
author: Dreieck52
version: 1.5

main: de.Dreieck52.LobbyCompass.LobbyCompass

commands:
    lobbycompass2:
        description: General LobbyCompass Command
        aliases: [lc2, lobbyc2, lcompass2, lcomp2]
